backend:
  name: isaac-martin

media_folder: static/assets
public_folder: assets

collections:
  - name: project
    label: Projects
    folder: projects
    create: true
    fields:
      - {name: path, label: Path}
      - {name: date, label: Date, widget: date}
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
