backend:
  name: github
  repo: isaac-martin/isaacmartin-2.0

media_folder: static/img
public_folder: /img

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/project'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Client', name: 'client', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'number' }
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
