backend:
  name: github
  repo: isaac-martin/isaacmartin-2.0

media_folder: static/img
public_folder: /img

collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/project'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Client', name: 'client', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'number' }
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/home/index.md'
        label: 'Home'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/build/index.md'
        label: 'Build'
        name: 'build'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'build',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
